name: Text Lint and Auto Request Review

on:
  pull_request:
  workflow_dispatch:

jobs:
  text-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Exec textlint
        uses: tsuyoshicho/action-textlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          textlint_flags: "site/ja/**"
  auto-request-review:
    if: contains(github.event.pull_request.requested_reviewers.*.login, '')
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/reviewers.yml"
