name: Text Lint and Auto Request Review

on:
  pull_request:
  workflow_dispatch:

jobs:
  auto-request-review:
    if: contains(github.event.pull_request.requested_reviewers.*.name, '')
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/reviewers.yml"
